/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.*;

import org.example.exception.InvalidApprovalException;
import org.example.model.*;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // requester made two requests
        Requester john = new Requester(1234, "john", "john@mail.com", "001");
        Request req = john.submitRequest(500, "USA travel", Category.Travel);
        Request req2 = john.submitRequest(1000, "Hotel Stay", Category.BusinessExpense);

        //all approvers approved
        List<Approver> approvers = req.getApprovers();
        try {
            for(Approver approver: approvers){
                approver.approveRequest(req);
            }
            System.out.println("Req Status: "+req.getStatus().toString());
        } catch (InvalidApprovalException e) {
            System.out.println(e.getMessage());
        }

        // if rejected byn one approver, others can not approve further
        List<Approver> approvers2 = req2.getApprovers();
        try{
            approvers2.get(0).rejectRequest(req2, "very expensive");
            approvers2.get(1).approveRequest(req2);
        } catch (InvalidApprovalException e) {
            System.out.println("exception on req 2: "+ e.getMessage());
        }
        System.out.println("Req2 Status: "+req2.getStatus().toString());

        // get all requests of user
        List<Request> requests = john.getRequestsMade();
        for(Request request: requests) {
            System.out.println(request.getReqestId() + " Status: "+ request.getStatus());
        }


    }
}
